# hahah

## 异常的捕获
异常并不完全是错误。
正如[python-1](../python-1/python-1.md)中yield部分中的例子，生成器对象在最后一次next操作时，会发生StopIteration异常。